# Generated by Django 4.2.5 on 2023-10-18 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
