# Generated by Django 4.2.5 on 2023-10-18 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_delete_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('about', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Topics',
                'ordering': ('name',),
            },
        ),
    ]
