# Generated by Django 4.2.5 on 2023-10-18 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
