# Generated by Django 4.2.5 on 2023-10-27 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_garden'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Garden',
            new_name='Garden_Pic',
        ),
    ]
