# Generated by Django 4.2.5 on 2023-10-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_project_image2_project_image3_project_image4'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pictures',
            field=models.URLField(blank=True, null=True),
        ),
    ]
