# Generated by Django 4.2.5 on 2023-11-22 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_project_pictures'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='front_page',
            field=models.BooleanField(default=False),
        ),
    ]
