# Generated by Django 4.2.5 on 2023-11-20 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adafruit_username', models.CharField(max_length=75)),
                ('adafruit_key', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Santa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
            ],
        ),
    ]
