# Generated by Django 4.2.5 on 2023-11-20 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0002_gift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='giftee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='santas', to='browse.santa'),
        ),
    ]
