# Generated by Django 4.2.5 on 2023-11-22 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0003_alter_gift_giftee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gift',
            old_name='gifter',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='gift',
            name='giftee',
        ),
        migrations.AddField(
            model_name='gift',
            name='number',
            field=models.IntegerField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gift',
            name='password',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
