# Generated by Django 4.2.5 on 2023-11-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0005_remove_gift_number_remove_gift_password_gift_chosen'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='giftee',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
