# Generated by Django 4.2.5 on 2023-11-25 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0006_gift_giftee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gift',
            name='giftee',
        ),
        migrations.AddField(
            model_name='gift',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
