# Generated by Django 4.2.5 on 2023-11-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0007_remove_gift_giftee_gift_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gifter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=75, null=True)),
                ('chosen', models.BooleanField(default=False)),
                ('number', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
