# Generated by Django 4.2.5 on 2023-11-26 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('browse', '0008_gifter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gift',
        ),
        migrations.RemoveField(
            model_name='gifter',
            name='chosen',
        ),
        migrations.RemoveField(
            model_name='gifter',
            name='name',
        ),
        migrations.AddField(
            model_name='gifter',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='numbers', to=settings.AUTH_USER_MODEL),
        ),
    ]
