# Generated by Django 4.2.5 on 2024-09-15 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terrarium', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='name',
            field=models.CharField(max_length=2555),
        ),
    ]
