# Generated by Django 4.2.5 on 2024-09-15 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terrarium', '0002_alter_plant_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terrarium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2555)),
                ('image', models.ImageField(blank=True, null=True, upload_to='terrarium_images')),
                ('plant1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant', to='terrarium.plant')),
                ('plant2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant2', to='terrarium.plant')),
                ('plant3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant3', to='terrarium.plant')),
                ('plant4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plant4', to='terrarium.plant')),
            ],
        ),
    ]
