# Generated by Django 4.2.5 on 2024-09-15 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terrarium', '0003_terrarium'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='pictures',
            new_name='link',
        ),
    ]
