# Generated by Django 4.2.5 on 2024-09-15 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terrarium', '0004_rename_pictures_plant_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terrarium',
            name='plant3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plant3', to='terrarium.plant'),
        ),
    ]
