# Generated by Django 4.2.5 on 2024-02-12 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonPlayerCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='project_images')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='project_images')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='project_images')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='project_images')),
                ('invisible', models.BooleanField(default=False)),
                ('pictures', models.URLField(blank=True, null=True)),
                ('affiliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='npc', to='dnd.affiliation')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='npc', to='dnd.race')),
            ],
            options={
                'verbose_name_plural': 'NPCs',
                'ordering': ('name',),
            },
        ),
    ]
