# Generated by Django 4.2.5 on 2024-02-12 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0002_nonplayercharacter'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonplayercharacter',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
