# Generated by Django 4.2.5 on 2024-02-12 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0003_nonplayercharacter_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonplayercharacter',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='nonplayercharacter',
            name='height',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
