# Generated by Django 4.2.5 on 2024-02-28 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0004_nonplayercharacter_age_nonplayercharacter_height'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField(null=True)),
                ('height', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('hp', models.IntegerField(null=True)),
                ('dex', models.IntegerField(null=True)),
                ('con', models.IntegerField(null=True)),
                ('int', models.IntegerField(null=True)),
                ('wis', models.IntegerField(null=True)),
                ('cha', models.IntegerField(null=True)),
                ('ac', models.IntegerField(null=True)),
                ('speed', models.CharField(blank=True, max_length=255, null=True)),
                ('abilities', models.TextField(blank=True, null=True)),
                ('actions', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='project_images')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='project_images')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='project_images')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='project_images')),
                ('invisible', models.BooleanField(default=False)),
                ('pictures', models.URLField(blank=True, null=True)),
                ('affiliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enemy', to='dnd.affiliation')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enemy', to='dnd.race')),
            ],
            options={
                'verbose_name_plural': 'Enemies',
                'ordering': ('name',),
            },
        ),
    ]
