# Generated by Django 4.2.5 on 2024-03-25 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0011_race_darkvision'),
    ]

    operations = [
        migrations.CreateModel(
            name='skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'skills',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Character_Sheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('character_name', models.CharField(blank=True, max_length=255, null=True)),
                ('lvl', models.IntegerField(null=True)),
                ('inspiration', models.IntegerField(null=True)),
                ('proficiency', models.IntegerField(null=True)),
                ('personality_traits', models.TextField(blank=True, null=True)),
                ('ideals', models.TextField(blank=True, null=True)),
                ('bonds', models.TextField(blank=True, null=True)),
                ('flaws', models.TextField(blank=True, null=True)),
                ('hp', models.IntegerField(null=True)),
                ('str', models.IntegerField(null=True)),
                ('dex', models.IntegerField(null=True)),
                ('con', models.IntegerField(null=True)),
                ('int', models.IntegerField(null=True)),
                ('wis', models.IntegerField(null=True)),
                ('cha', models.IntegerField(null=True)),
                ('ac', models.IntegerField(null=True)),
                ('speed', models.CharField(blank=True, max_length=255, null=True)),
                ('abilities', models.TextField(blank=True, null=True)),
                ('actions', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='project_images')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='project_images')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='project_images')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='project_images')),
                ('invisible', models.BooleanField(default=False)),
                ('pictures', models.URLField(blank=True, null=True)),
                ('affiliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character', to='dnd.affiliation')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character', to='dnd.race')),
            ],
            options={
                'verbose_name_plural': 'Character_Sheets',
                'ordering': ('name',),
            },
        ),
    ]
