# Generated by Django 4.2.5 on 2024-03-25 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0012_skill_character_sheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='character_sheet',
            name='proficient_skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill', to='dnd.skill'),
        ),
    ]
