# Generated by Django 4.2.5 on 2024-03-25 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0013_character_sheet_proficient_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='character_sheet',
            name='skill_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill2', to='dnd.skill'),
        ),
        migrations.AddField(
            model_name='character_sheet',
            name='skill_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill3', to='dnd.skill'),
        ),
        migrations.AddField(
            model_name='character_sheet',
            name='skill_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill4', to='dnd.skill'),
        ),
        migrations.AddField(
            model_name='character_sheet',
            name='skill_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill5', to='dnd.skill'),
        ),
        migrations.AddField(
            model_name='character_sheet',
            name='skill_6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill6', to='dnd.skill'),
        ),
        migrations.AddField(
            model_name='character_sheet',
            name='skill_7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill7', to='dnd.skill'),
        ),
        migrations.AddField(
            model_name='character_sheet',
            name='skill_8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill8', to='dnd.skill'),
        ),
    ]
