# Generated by Django 4.2.5 on 2024-03-25 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0014_character_sheet_skill_2_character_sheet_skill_3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('damage', models.CharField(max_length=255)),
                ('bonus', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name_plural': 'weapons',
                'ordering': ('name',),
            },
        ),
        migrations.RemoveField(
            model_name='character_sheet',
            name='abilities',
        ),
        migrations.RemoveField(
            model_name='character_sheet',
            name='actions',
        ),
        migrations.AddField(
            model_name='character_sheet',
            name='equipment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character_sheet',
            name='weapon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weapon', to='dnd.weapon'),
        ),
        migrations.AddField(
            model_name='character_sheet',
            name='weapon_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weapon2', to='dnd.weapon'),
        ),
        migrations.AddField(
            model_name='character_sheet',
            name='weapon_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weapon3', to='dnd.weapon'),
        ),
    ]
