# Generated by Django 4.2.5 on 2024-03-25 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0016_remove_weapon_bonus_character_sheet_weapon2_bonus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill_Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'classes',
                'ordering': ('name',),
            },
        ),
    ]
