# Generated by Django 4.2.5 on 2024-03-26 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0017_skill_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character_sheet',
            name='affiliation',
        ),
        migrations.AddField(
            model_name='character_sheet',
            name='skill_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='character', to='dnd.skill_class'),
        ),
    ]
