# Generated by Django 4.2.5 on 2024-03-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0018_remove_character_sheet_affiliation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character_sheet',
            name='inspiration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='character_sheet',
            name='proficiency',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='character_sheet',
            name='weapon2_bonus',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='character_sheet',
            name='weapon3_bonus',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='character_sheet',
            name='weapon_bonus',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
