# Generated by Django 4.2.5 on 2024-03-30 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0019_alter_character_sheet_inspiration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('damage', models.TextField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'spells',
                'ordering': ('name',),
            },
        ),
    ]
