# Generated by Django 4.2.5 on 2024-03-30 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0023_alter_spell_damage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spell',
            old_name='damage',
            new_name='description',
        ),
    ]
