# Generated by Django 4.2.5 on 2024-03-30 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0024_rename_damage_spell_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='character_sheet',
            name='spell_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character_sheet',
            name='spell_link10',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character_sheet',
            name='spell_link2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character_sheet',
            name='spell_link3',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character_sheet',
            name='spell_link4',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character_sheet',
            name='spell_link5',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character_sheet',
            name='spell_link6',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character_sheet',
            name='spell_link7',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character_sheet',
            name='spell_link8',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character_sheet',
            name='spell_link9',
            field=models.URLField(blank=True, null=True),
        ),
    ]
