# Generated by Django 4.2.5 on 2024-03-31 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0025_character_sheet_spell_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='description',
            field=models.TextField(max_length=4088),
        ),
    ]
