# Generated by Django 4.2.5 on 2024-03-31 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0026_alter_spell_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='DM_Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('link', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'dm options',
                'ordering': ('name',),
            },
        ),
    ]
