# Generated by Django 4.2.5 on 2024-03-31 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0027_dm_menu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dm_menu',
            options={'ordering': ('name',), 'verbose_name_plural': 'dm Options'},
        ),
    ]
