# Generated by Django 4.2.5 on 2024-03-31 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0028_alter_dm_menu_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='project_images')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='project_images')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='project_images')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='project_images')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='project_images')),
                ('image6', models.ImageField(blank=True, null=True, upload_to='project_images')),
                ('image7', models.ImageField(blank=True, null=True, upload_to='project_images')),
                ('image8', models.ImageField(blank=True, null=True, upload_to='project_images')),
                ('link', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'maps',
                'ordering': ('name',),
            },
        ),
    ]
