# Generated by Django 4.2.5 on 2024-04-01 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0029_map'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=4088)),
            ],
            options={
                'verbose_name_plural': 'treasures',
                'ordering': ('name',),
            },
        ),
    ]
