# Generated by Django 4.2.5 on 2024-04-01 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0033_alter_map_monsters1_alter_map_monsters2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monster',
            old_name='spell_link',
            new_name='link',
        ),
    ]
