# Generated by Django 4.2.5 on 2024-04-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0034_rename_spell_link_monster_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
