# Generated by Django 4.2.5 on 2024-04-28 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0035_map_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='character_sheet',
            name='spell11',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spell11', to='dnd.spell'),
        ),
        migrations.AddField(
            model_name='character_sheet',
            name='spell12',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spell12', to='dnd.spell'),
        ),
        migrations.AddField(
            model_name='character_sheet',
            name='spell13',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spell13', to='dnd.spell'),
        ),
        migrations.AddField(
            model_name='character_sheet',
            name='spell14',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spell14', to='dnd.spell'),
        ),
        migrations.AddField(
            model_name='character_sheet',
            name='spell15',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spell15', to='dnd.spell'),
        ),
        migrations.AddField(
            model_name='character_sheet',
            name='spell16',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spell16', to='dnd.spell'),
        ),
        migrations.AddField(
            model_name='character_sheet',
            name='spell17',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spell17', to='dnd.spell'),
        ),
        migrations.AddField(
            model_name='character_sheet',
            name='spell_link11',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character_sheet',
            name='spell_link12',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character_sheet',
            name='spell_link13',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character_sheet',
            name='spell_link14',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character_sheet',
            name='spell_link15',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character_sheet',
            name='spell_link16',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character_sheet',
            name='spell_link17',
            field=models.URLField(blank=True, null=True),
        ),
    ]
