# Generated by Django 4.2.5 on 2024-05-22 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0036_character_sheet_spell11_character_sheet_spell12_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Special_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=4088)),
            ],
            options={
                'verbose_name_plural': 'special items',
                'ordering': ('name',),
            },
        ),
    ]
