# Generated by Django 4.2.5 on 2024-05-23 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0040_special_item_lvl1_special_item_lvl2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='special_item',
            name='shop1_img',
            field=models.ImageField(blank=True, null=True, upload_to='shop1_images'),
        ),
        migrations.AddField(
            model_name='special_item',
            name='shop2_img',
            field=models.ImageField(blank=True, null=True, upload_to='shop2_images'),
        ),
        migrations.AddField(
            model_name='special_item',
            name='shop3_img',
            field=models.ImageField(blank=True, null=True, upload_to='shop3_images'),
        ),
        migrations.AddField(
            model_name='special_item',
            name='shop4_img',
            field=models.ImageField(blank=True, null=True, upload_to='shop4_images'),
        ),
        migrations.AddField(
            model_name='special_item',
            name='shop5_img',
            field=models.ImageField(blank=True, null=True, upload_to='shop5_images'),
        ),
        migrations.AddField(
            model_name='special_item',
            name='shop6_img',
            field=models.ImageField(blank=True, null=True, upload_to='shop6_images'),
        ),
    ]
