# Generated by Django 4.2.5 on 2024-05-23 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0041_special_item_shop1_img_special_item_shop2_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='special_item',
            name='shop1_img',
        ),
        migrations.RemoveField(
            model_name='special_item',
            name='shop2_img',
        ),
        migrations.RemoveField(
            model_name='special_item',
            name='shop3_img',
        ),
        migrations.RemoveField(
            model_name='special_item',
            name='shop4_img',
        ),
        migrations.RemoveField(
            model_name='special_item',
            name='shop5_img',
        ),
        migrations.RemoveField(
            model_name='special_item',
            name='shop6_img',
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop_images')),
                ('items', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='special_items', to='dnd.special_item')),
            ],
            options={
                'verbose_name_plural': 'shops',
                'ordering': ('name',),
            },
        ),
    ]
