# Generated by Django 4.2.5 on 2024-05-23 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0042_remove_special_item_shop1_img_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='items',
            new_name='item1',
        ),
    ]
