# Generated by Django 4.2.5 on 2024-05-23 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0043_rename_items_shop_item1'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='item2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='special_items2', to='dnd.special_item'),
        ),
        migrations.AddField(
            model_name='shop',
            name='item3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='special_items3', to='dnd.special_item'),
        ),
        migrations.AddField(
            model_name='shop',
            name='item4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='special_items4', to='dnd.special_item'),
        ),
        migrations.AddField(
            model_name='shop',
            name='item5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='special_items5', to='dnd.special_item'),
        ),
        migrations.AddField(
            model_name='shop',
            name='item6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='special_items6', to='dnd.special_item'),
        ),
    ]
