# Generated by Django 4.2.5 on 2024-05-23 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0044_shop_item2_shop_item3_shop_item4_shop_item5_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='item7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='special_items7', to='dnd.special_item'),
        ),
    ]
