# Generated by Django 4.2.5 on 2024-05-24 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0047_character_sheet_special_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='special_item',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
